#!/bin/sh

# Sanity checks
test -f /etc/mpd.conf || exit 0

start() {
	printf "Starting WPA SUPPLICANT: "
	/usr/sbin/wpa_supplicant -B -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf
}

stop() {
       printf "Stoping WPA SUPPLICANT"
       killall wpa_supplicant
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
