#!/bin/bash
(
 cd buildroot-2021.02
 ./output/host/bin/qemu-system-aarch64 \
  -M virt -cpu cortex-a53 -nographic -smp 1 \
  -bios output/images/u-boot.bin \
  -netdev user,id=eth0,hostfwd=tcp::8888-:8810,hostfwd=tcp::2222-:22 \
  -drive file=output/images/sdcard.img,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 \
  -device virtio-net-device,netdev=eth0 \
  -soundhw hda -audiodev id=pa,driver=pa
)

# -drive file=output/images/rootfs.ext2,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0
 